name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test -- --browsers=ChromeHeadless --watch=false

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: gmf-training 

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gmf-training 

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t gcr.io/gmf-training/dev-frontend-web-server:${{ env.IMAGE_TAG }} .
          docker tag gcr.io/gmf-training/dev-frontend-web-server:${{ env.IMAGE_TAG }} gcr.io/gmf-training/dev-frontend-web-server:latest

      - name: Push Docker images
        run: |
          docker push gcr.io/gmf-training/dev-frontend-web-server:${{ env.IMAGE_TAG }}
          docker push gcr.io/gmf-training/dev-frontend-web-server:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dev-frontend-service \
          --image gcr.io/gmf-training/dev-frontend-web-server:${{ env.IMAGE_TAG }} \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated \
          --set-env-vars "API_URL=https://dev-api.gmf-aeroasia.publicvm.com"